# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4885ac89-2fbf-480e-b755-2cd47eb59879";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."nixos-crypt".device = "/dev/disk/by-uuid/3aeddb9a-58e4-4ee3-b188-cd523efa3d95";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/90BB-1FA8";
      fsType = "vfat";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 8;
}
